/**
 * Database Seed Runner
 *
 * Inserts canonical fixture records used by integration tests and smoke tests.
 * Fully idempotent — safe to run multiple times.
 *
 * Usage:
 *   npm run db:seed
 */

import 'dotenv/config';
import bcrypt from 'bcryptjs';
import { DatabaseClient } from '../src/backend/database/client';

async function seed(): Promise<void> {
  const db = DatabaseClient.getInstance();
  console.log('Seeding database…\n');

  const hash = await bcrypt.hash('SecurePassword123!', 12);
  console.log('  ✓ bcrypt hash generated');

  // ── 1. Roles (upsert by name — name is the stable key) ───────────────────
  await db.query(`
    INSERT INTO roles (name, description, permissions) VALUES
      ('ADMIN',       'Full system access',
       '["*"]'::jsonb),
      ('SOC_ANALYST', 'SOC analyst permissions',
       '["alert:read","alert:create","alert:update","case:read","case:create","case:update","investigation:read","investigation:create","report:read"]'::jsonb),
      ('VIEWER',      'Read-only access',
       '["alert:read","case:read","report:read"]'::jsonb)
    ON CONFLICT (name) DO UPDATE SET
      permissions = EXCLUDED.permissions,
      description = EXCLUDED.description
  `);
  console.log('  ✓ roles seeded');

  // Fetch actual role IDs (auto-generated by DB)
  const roles = await db.query<{ id: string; name: string }>(
    'SELECT id, name FROM roles WHERE name IN ($1,$2,$3)',
    ['ADMIN', 'SOC_ANALYST', 'VIEWER']
  );
  const roleId = (name: string): string => {
    const r = roles.find(r => r.name === name);
    if (!r) throw new Error(`Role not found: ${name}`);
    return r.id;
  };

  // ── 2. Users (upsert by email) ────────────────────────────────────────────
  await db.query(`
    INSERT INTO users (username, email, password_hash, role_id, status) VALUES
      ('admin',    'admin@soc.local',    $1, $2, 'active'),
      ('analyst1', 'analyst1@soc.local', $1, $3, 'active'),
      ('viewer1',  'viewer1@soc.local',  $1, $4, 'active')
    ON CONFLICT (email) DO UPDATE SET
      password_hash = EXCLUDED.password_hash,
      role_id       = EXCLUDED.role_id,
      status        = EXCLUDED.status
  `, [hash, roleId('ADMIN'), roleId('SOC_ANALYST'), roleId('VIEWER')]);
  console.log('  ✓ users seeded');

  // Fetch user IDs for FK references
  const users = await db.query<{ id: string; email: string }>(
    'SELECT id, email FROM users WHERE email IN ($1,$2,$3)',
    ['admin@soc.local', 'analyst1@soc.local', 'viewer1@soc.local']
  );
  const userId = (email: string): string => {
    const u = users.find(u => u.email === email);
    if (!u) throw new Error(`User not found: ${email}`);
    return u.id;
  };

  // ── 3. Detection Rules ───────────────────────────────────────────────────
  await db.query(`
    INSERT INTO detection_rules
      (name, description, rule_type, severity, status, mitre_technique_id, rule_definition, enabled)
    VALUES
      ('SSH Brute Force Threshold',
       'Fires after 5 failed SSH attempts from a single source within 300 seconds',
       'threshold', 'high', 'production', 'T1110.001',
       '{"condition":"multiple_failed_logins","threshold":5,"timeWindow":300}'::jsonb, true),
      ('SQLi Payload Detection',
       'Regex matching SQL injection payloads in HTTP requests',
       'atomic', 'critical', 'production', 'T1190',
       '{"condition":"sqli_payload_match","pattern":"(?i)(union.*select)"}'::jsonb, true)
    ON CONFLICT DO NOTHING
  `);
  console.log('  ✓ detection rules seeded');

  // ── 4. Alerts ────────────────────────────────────────────────────────────
  await db.query(`
    INSERT INTO alerts
      (title, description, severity, status, alert_type, source_system, source_ip, created_by)
    VALUES
      ('SSH Brute Force Detected',
       'Multiple failed SSH authentication attempts from 10.0.0.55',
       'high', 'open', 'brute_force', 'wazuh', '10.0.0.55', 'system'),
      ('SQL Injection Attempt',
       'SQLi payload detected against DVWA login form',
       'critical', 'acknowledged', 'web_attack', 'wazuh', '10.0.0.77', 'system'),
      ('Suspicious Python Execution',
       'Unusual python process spawned by web server user',
       'medium', 'resolved', 'suspicious_execution', 'auditd', null, 'system')
    ON CONFLICT DO NOTHING
  `);
  console.log('  ✓ alerts seeded');

  // ── 5. Cases ─────────────────────────────────────────────────────────────
  await db.query(`
    INSERT INTO cases
      (case_number, title, description, severity, status, priority, created_by_id, assigned_to_id)
    VALUES
      ('CASE-2026-0001',
       'Brute Force Campaign Investigation',
       'Investigate repeated SSH brute force activity against monitored host',
       'high', 'investigating', 'high', $1, $2),
      ('CASE-2026-0002',
       'Web Attack Against DVWA',
       'SQL injection attempts against the DVWA target',
       'critical', 'open', 'critical', $1, NULL)
    ON CONFLICT (case_number) DO NOTHING
  `, [userId('admin@soc.local'), userId('analyst1@soc.local')]);
  console.log('  ✓ cases seeded');

  // Fetch case IDs for investigation FK
  const cases = await db.query<{ id: string; case_number: string }>(
    "SELECT id, case_number FROM cases WHERE case_number = 'CASE-2026-0001'"
  );

  // ── 6. Investigations ────────────────────────────────────────────────────
  if (cases.length > 0) {
    await db.query(`
      INSERT INTO investigations
        (case_id, title, description, investigator_id, status, timeline_events)
      VALUES ($1, $2, $3, $4, 'active', $5::jsonb)
      ON CONFLICT DO NOTHING
    `, [
      cases[0].id,
      'Brute Force Timeline Analysis',
      'Timeline reconstruction of the SSH brute force campaign',
      userId('analyst1@soc.local'),
      JSON.stringify([
        { timestamp: '2026-10-01T08:14:55.000Z', eventType: 'auth_failure', source: 'wazuh', description: 'Failed SSH login for root from 10.0.0.55' },
        { timestamp: '2026-10-01T08:15:10.000Z', eventType: 'auth_failure', source: 'wazuh', description: 'Failed SSH login for admin from 10.0.0.55' },
        { timestamp: '2026-10-01T08:15:30.000Z', eventType: 'alert_generated', source: 'wazuh', description: 'Rule threshold reached - alert raised' },
        { timestamp: '2026-10-01T09:00:00.000Z', eventType: 'case_opened', source: 'soc-lab', description: 'Case CASE-2026-0001 opened' },
      ]),
    ]);
  }
  console.log('  ✓ investigations seeded');

  // ── 7. Reports ───────────────────────────────────────────────────────────
  await db.query(`
    INSERT INTO reports
      (title, report_type, status, generated_by_id, report_data, file_format)
    VALUES
      ('Weekly Detection Coverage Report', 'coverage', 'completed', $1,
       '{"summary":"8/8 techniques detected in the evaluation window","period":"weekly"}'::jsonb,
       'pdf')
    ON CONFLICT DO NOTHING
  `, [userId('analyst1@soc.local')]);
  console.log('  ✓ reports seeded');

  console.log('\nSeed complete.');
  await db.end();
}

seed().catch(err => {
  console.error('Seed failed:', (err as Error).message);
  process.exit(1);
});
