#!/usr/bin/env bash
# SOC Detection Lab — Smoke Test
#
# Verifies the deployed stack end-to-end: health, authentication, and the
# core alert/case workflows. Expects the API on $BASE_URL (default
# http://localhost:3000/api/v1) and the seeded admin account.
#
# Usage:
#   bash scripts/smoke-test.sh
#   BASE_URL=https://soc.example.com/api/v1 bash scripts/smoke-test.sh

set -euo pipefail

BASE_URL="${BASE_URL:-http://localhost:3000/api/v1}"
EMAIL="${SOC_ADMIN_EMAIL:-admin@soc.local}"
PASSWORD="${SOC_ADMIN_PASSWORD:-SecurePassword123!}"

PASS=0
FAIL=0

check() {
  local name="$1" expected="$2" actual="$3"
  if [ "$actual" = "$expected" ]; then
    echo "✓ $name (HTTP $actual)"
    PASS=$((PASS + 1))
  else
    echo "✗ $name — expected HTTP $expected, got HTTP $actual"
    FAIL=$((FAIL + 1))
  fi
}

status_of() {
  curl -s -o /dev/null -w '%{http_code}' "$@"
}

echo "══════════════════════════════════════════"
echo " SOC Detection Lab — Smoke Test"
echo " Target: $BASE_URL"
echo "══════════════════════════════════════════"

# 1. Health
check "health endpoint" 200 "$(status_of "$BASE_URL/health")"

# 2. Login
LOGIN_RESPONSE=$(curl -s -X POST "$BASE_URL/auth/login" \
  -H 'Content-Type: application/json' \
  -d "{\"email\":\"$EMAIL\",\"password\":\"$PASSWORD\"}")
TOKEN=$(echo "$LOGIN_RESPONSE" | grep -o '"accessToken":"[^"]*' | cut -d'"' -f4)

if [ -n "$TOKEN" ]; then
  echo "✓ login issued an access token"
  PASS=$((PASS + 1))
else
  echo "✗ login failed — no access token in response"
  FAIL=$((FAIL + 1))
fi

AUTH="Authorization: Bearer $TOKEN"

# 3. Alerts workflow
check "list alerts" 200 "$(status_of "$BASE_URL/alerts" -H "$AUTH")"
check "alert stats" 200 "$(status_of "$BASE_URL/alerts/stats/summary" -H "$AUTH")"

CREATED=$(curl -s -X POST "$BASE_URL/alerts" -H "$AUTH" -H 'Content-Type: application/json' \
  -d '{"title":"Smoke Test Alert","description":"Generated by smoke-test.sh","severity":"low","alertType":"smoke_test"}')
ALERT_ID=$(echo "$CREATED" | grep -o '"id":"[^"]*' | head -1 | cut -d'"' -f4)

if [ -n "$ALERT_ID" ]; then
  echo "✓ created alert $ALERT_ID"
  PASS=$((PASS + 1))
  check "acknowledge alert" 200 "$(status_of -X POST "$BASE_URL/alerts/$ALERT_ID/acknowledge" -H "$AUTH" -H 'Content-Type: application/json' -d '{}')"
  check "delete alert" 204 "$(status_of -X DELETE "$BASE_URL/alerts/$ALERT_ID" -H "$AUTH")"
else
  echo "✗ alert creation failed"
  FAIL=$((FAIL + 1))
fi

# 4. Cases workflow
check "list cases" 200 "$(status_of "$BASE_URL/cases" -H "$AUTH")"
check "case stats" 200 "$(status_of "$BASE_URL/cases/stats/summary" -H "$AUTH")"

# 5. RBAC + profile
check "list roles" 200 "$(status_of "$BASE_URL/rbac/roles" -H "$AUTH")"
check "current profile" 200 "$(status_of "$BASE_URL/users/me/profile" -H "$AUTH")"

# 6. Unauthenticated access is rejected
check "unauthenticated list rejected" 401 "$(status_of "$BASE_URL/alerts")"

echo "══════════════════════════════════════════"
echo " Results: $PASS passed, $FAIL failed"
echo "══════════════════════════════════════════"

[ "$FAIL" -eq 0 ]
